trigger:
  branches:
    include:
      - master

pool:
  name: 'Default'  # Reference your self-hosted agent pool

variables:
  imageName: 'sbk8stutorialacr.azurecr.io/demo'

jobs:
  - job: Build
    pool: 'Default'  # Ensure each job uses the self-hosted agent pool
    steps:
      - task: Maven@3
        inputs:
          goals: 'package'
          options: '-DskipTests'

  - job: Docker
    dependsOn: Build
    pool: 'Default'  # Ensure each job uses the self-hosted agent pool
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acr-connection'  # Add your ACR service connection
          repository: $(imageName)
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildId)
