trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'sbk8stutorialacr.azurecr.io/demo'

jobs:
  - job: Build
    steps:
      - task: Maven@3
        inputs:
          goals: 'package'
          options: '-DskipTests'

  - job: Docker
    dependsOn: Build
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acr-connection'  # Add your ACR service connection
          repository: $(imageName)
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |
            $(Build.BuildId)
